defaults:
  - override /trainer@_global_: base_sft
  - override /model@_global_: qwen3_8b
  - override /data@_global_: arc_atlas_sft
  - _self_

# Minimal configuration for 5-minute quickstart validation
# Optimized for speed over quality - DO NOT use for production

bf16: true
tf32: true

# Quick validation - only 10 steps
max_steps: 10
num_train_epochs: 1

# Skip evaluation for speed
do_eval: false
eval_strategy: "no"

# Small batches for quick iteration
train_batch_size: 4
per_device_train_batch_size: 1
gradient_accumulation_steps: ???

# Memory optimization
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

# Standard learning parameters
learning_rate: 1.0e-05
weight_decay: 1e-4
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1e-8
max_grad_norm: 1.0

lr_scheduler_type: constant
warmup_steps: 0

# Minimal logging
logging_steps: 5
logging_strategy: steps

# Reduced context for speed
packing: false
max_seq_length: 2048

# Disable external logging for quickstart
report_to: null
push_to_hub: false

# Skip model saving for speed
save_strategy: "no"
save_final_model: false

# Quick output directory
output_dir: ${results_dir}/quickstart_sft

# No wandb for quickstart
wandb_project: null
wandb_run_name: null