agents:
  target:
    provider: http.api
    params:
      endpoint: "http://localhost:8000/chat"
      prompt_field: "message"
      response_field: "response"
      request_template:
        message: ""
      headers:
        Authorization: "Bearer YOUR_KEY"
      timeout: 300

teacher_model: Arc-Intelligence/ATLAS-8B-Thinking

trainset: arc-atlas-rl
max_examples: 10
compatibility_mode: true

max_metric_calls: 100
reflection_lm: gpt-4
trace_storage: traces/compatibility_traces.jsonl
output: compatibility_results.json

use_vllm_client: false
vllm_host: localhost
vllm_port: 8765

max_litellm_workers: 10

generation_config:
  max_tokens: 2048
  temperature: 0.7
  diagnostic_max_tokens: 500
  timeout: 300
  request_timeout: 300

seed_prompts:
  teacher_adaptive_template: "You are an expert teacher. The student gave this response: {baseline_response}\n\nTo the question: {question}\n\nProvide focused teaching to help them improve. Wrap teaching in <teaching> tags."

wandb:
  enabled: false
  project: atlas-compatibility-testing
  run_name: null
  tags:
    - compatibility
    - existing-agent
  notes: "Testing existing agent with ATLAS teaching"
