# Minimal GRPO quickstart config for running on exported runtime traces.
# Usage:
#   python train.py --config-name examples/quickstart
# or run the helper script:
#   python scripts/run_offline_pipeline.py --export-path traces/aime-batch.jsonl

defaults:
  - /train

# Path to the runtime dataset exported from the atlas-sdk CLI.
data:
  dataset_path: traces/aime-batch.jsonl
  eval_split_ratio: 0.1

# Optional overrides for experiment tracking and output structure.
wandb_project: atlas-quickstart
wandb_run_name: traces-to-grpo
output_dir: results/quickstart
