services:
  postgres:
    container_name: atlas-postgres
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: atlas
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas
    volumes:
      - atlas_pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  atlas_pg_data:
    driver: local
