defaults:
  - ../optimize/default

max_metric_calls: 5
capture_traces: true

user_agent:
  type: custom
  config:
    integration_type: python_function
    module_path: "ITBench-SRE-Agent/src/lumyn/crew.py"
    module_base_path: "ITBench-SRE-Agent/src"
    class_name: "LumynCrew"
    function_name: "kickoff"
    process_input: "dict_wrapper"
    input_key: "alerts"
    process_response: "json"
    suppress_output: true

max_examples: 5

data_source:
  type: itbench_scenarios
  scenarios_dir: ITBench-Scenarios/sre/roles/incidents/files

data:
  columns:
    question: "alerts"

seed_prompts:
  teacher_adaptive_template: |
    You are a adaptive teacher reviewing a student for SRE tasks diagnostic approach.

    Incident Details: {question}

    Student Proposed Approach: {approach}

    Available Tools the Student Can Use:
    {available_tools}

    Review their diagnostic approach and provide guidance:
    1. Point out any missed investigation steps should be consider
    2. Identify areas they should check but haven't mentioned
    3. Suggest better techniques for this type of incident using the available tools
    4. Highlight any overlooked symptoms or correlations they should investigate
    5. Recommend specific tools from the available set that would be most effective

    Focus on improving their investigation approach before they execute.
    And If Student is right and not made any mistake in there apporach then agree with the approach and tell student to go ahead.
    Wrap your teaching in <teaching> tags.

  student_diagnostic_template: |
    You are an SRE agent investigating: {question}

    List your diagnostic steps concisely:
    - Key entities to check
    - Fault propagation path
    - Critical metrics/logs

    Be brief and direct. No explanations needed. 
    And if you are confuse on any part ask the teacher for which you are providing the apporach.

  student_with_teaching_template: |
    You are an SRE agent investigating a production incident.

    {question}

    Your Initial Diagnostic Approach:
    {approach}

    Teacher Guidance:
    {teaching}

    Now execute your diagnostic approach with the Teacher corrections and guidance if any do not think directly go the implementation:
    - Use the diagnostic techniques suggested
    - Check for the specific issues mentioned
    - Follow the recommended investigation path
    - Ensure complete fault chain analysis

    Output a JSON diagnosis with this EXACT structure:
    ```json
    {{
      "entities": [
        {{"id": "entity_identifier", "root_cause": true/false}}
      ],
      "propagations": [
        {{"source": "source_entity", "target": "target_entity", "condition": "how it propagated", "effect": "what happened"}}
      ]
    }}
    ```

optimization_targets:
  teacher_adaptive_template:
    optimize: true
    reflection_goal: "Improve SRE agent's ability to identify root causes and fault propagation chains"

  student_diagnostic_template:
    optimize: true
    reflection_goal: "Improve initial diagnostic approach for faster root cause discovery"

  student_with_teaching_template:
    optimize: true
    reflection_goal: "Better integrate teaching guidance to improve diagnosis accuracy"

reflection_instructions:
  teacher_adaptive_template: |
    OPTIMIZATION TARGET: teacher_adaptive_template
    GOAL: Improve teaching effectiveness for SRE incident diagnosis

    CURRENT TEMPLATE:
    {current_template}

    ITERATION RESULTS:
    {performance_data}

    RIM EVALUATION ANALYSIS:
    Each sample includes RIM evaluation with:
    - rim_rewards: Scores for accuracy, helpfulness, process, diagnostic
    - rim_explanations: Principle-based reasoning for each score

    INSTRUCTIONS:
    1. Review RIM explanations for helpfulness and diagnostic scores
    2. Identify which principles are consistently violated in low-scoring examples
    3. Find patterns: What teaching approaches led to principle violations?
    4. Note which principles were satisfied in high-scoring examples

    TASK: Generate an IMPROVED teaching template that:
    - Addresses principle violations identified by RIM
    - Incorporates patterns from high-scoring examples
    - Ensures teaching satisfies the principles RIM uses for evaluation

    Return ONLY the improved template text, maintaining {question} and {approach} placeholders.

  student_diagnostic_template: |
    OPTIMIZATION TARGET: student_diagnostic_template
    GOAL: Improve initial diagnostic approach for SRE incidents

    CURRENT TEMPLATE:
    {current_template}

    ITERATION RESULTS:
    {performance_data}

    RIM EVALUATION ANALYSIS:
    Each sample includes RIM evaluation with:
    - rim_rewards: Scores for accuracy, helpfulness, process, diagnostic
    - rim_explanations: Principle-based reasoning for each score

    INSTRUCTIONS:
    1. Review RIM explanations for process scores
    2. Identify which principles for plan quality are violated
    3. Find patterns: What aspects of diagnostic approach led to low process scores?
    4. Note which principles were satisfied in high-scoring diagnostic approaches

    TASK: Generate an IMPROVED diagnostic template that:
    - Addresses process principle violations identified by RIM
    - Ensures diagnostic approach satisfies RIM's evaluation principles
    - Leads to higher process scores by meeting principle requirements

    Return ONLY the improved template text, maintaining {question} placeholder.

  student_with_teaching_template: |
    OPTIMIZATION TARGET: student_with_teaching_template
    GOAL: Improve how teaching is integrated into student response

    CURRENT TEMPLATE:
    {current_template}

    ITERATION RESULTS:
    {performance_data}

    RIM EVALUATION ANALYSIS:
    Each sample includes RIM evaluation with:
    - rim_rewards: Scores for accuracy, helpfulness, process, diagnostic
    - rim_explanations: Principle-based reasoning for each score

    INSTRUCTIONS:
    1. Review RIM explanations for accuracy and helpfulness scores
    2. Identify cases where teaching was provided but not effectively applied
    3. Find patterns: Why did some students integrate teaching better than others?
    4. Note which principles were satisfied when teaching was well-integrated

    TASK: Generate an IMPROVED template that:
    - Addresses principle violations in how teaching is applied
    - Ensures student effectively integrates teacher guidance
    - Leads to higher accuracy and helpfulness scores

    Return ONLY the improved template text, maintaining {question} and {teaching} placeholders.


trace_storage: traces/itbench_traces.jsonl
output: traces/itbench_optimized.json


compatibility_mode: true

gepa_config:
  reflection_minibatch_size: 5
  candidate_selection_strategy: pareto
  skip_perfect_score: false
  perfect_score: 1.0
  module_selector: all