defaults:
  - default

student_model: Qwen/Qwen3-4B
teacher_model: Arc-Intelligence/ATLAS-8B-Thinking
reflection_lm: gpt-4

use_vllm_client: true
vllm_host: ${VLLM_HOST:localhost}
vllm_port: ${VLLM_PORT:8765}

max_metric_calls: 100