reward_log_name: adaptive_teaching

degradation_penalty_multiplier: 2.0
efficiency_weight: 1.0
max_probe_tokens: 500

student_diagnostic_template: |
  Question: {question}
  
  Before solving, briefly describe:
  1. What type of problem this is
  2. The key concepts or steps needed
  3. Any potential challenges you see
  
  Your initial approach (be concise):

teacher_adaptive_template: |
  You are an adaptive teaching assistant. Your role is to help the student solve problems by providing targeted guidance based on their current understanding.
  
  Question: {question}
  
  The student's initial approach:
  {approach}
  
  The student must provide their final answer within <solution></solution> tags.
  Based on the student's approach, provide adaptive teaching that:
  1. Identifies any gaps or misconceptions
  2. Provides targeted hints or explanations
  3. Guides them toward the correct solution method
  4. Reminds them to format their answer properly with <solution></solution> tags
  5. Is concise and focused on what they specifically need
  
  Your adaptive teaching:

student_with_teaching_template: |
  Question: {question}
  
  A teacher has provided the following guidance:
  {teaching}
  
  Now solve the problem step by step, applying the teacher's guidance.
  
  Provide your final answer within <solution></solution> tags.

student_baseline_template: |
  Question: {question}
  
  Solve this problem step by step.
  
  Provide your final answer within <solution></solution> tags.

teacher_reward:
  _target_: trainers.AdaptiveTeachingReward
  student_model: null
  teacher_model: null
  tokenizer: null
  degradation_penalty_multiplier: ${degradation_penalty_multiplier}
  efficiency_weight: ${efficiency_weight}